module.exports.config = {
	name: "florentino",
	version: "1.0.0",
	hasPermssion: 0,
	credits: "Phước(NVP)",
	description: "Flo vip pro",
	commandCategory: "Tấu Hài",
	cooldowns: 0
};

module.exports.run = ({ event, api }) => api.sendMessage(`Không biết anh BLACK có biết Tú có Ny hay không, chúng tôi biết rằng tú có ny là người chơi khá nổi tiếng với con bài Florentino, ngày hôm nay anh ta đi cầm Florentino và chơi rất hay, trận thi đấu vừa xong là trận thi đấu mà chúng ta có thể thấy rằng là các bạn khán giả cũng có kĩ năng rất tốt- đặc biệt là người chơi bên phía của đội tuyển Đồng 5 đội tuyển Trái Đất đó là Tú có Ny, tôi thấy rằng anh ta chưa để cái tốc biến mình hồi được hiện xanh quá lâu anh ta sử dụng ngay lập tức bằng những tình huống mở giao tranh của mình và chính Tú có Ny là MVP của trận thi đấu này với 14.0 điểm MVP \nMột tình huống mà có lẽ Flo đang làm quá nhiều điều, những tình huống bông muq muq muq muq, bỏ chạy với Flo, Flo đang múa quá nhức nách, phải nói là Flo võ công quá cao cường \nVà đây là Florentino, Florentino ui một cái tình huống phải nói là cực gắt. Tú có Ny và người chơi này có lẽ sẽ có Ny thôi, đánh quá ghê. Những tình huống bông hoa bông hủng phải nói là đúng top 1, buff bẩn Quá ghê gớm....🌚😳 \nVà đây là Folontilô!😱😱 \nFolontilô ui... 🥶🥶👿😳một tình huống múa phải nói là cực 👿gắt!! \n*music🤯 \nThẹn thùng nhìn em quay gót đi mãi😞😞💔 \nAnh đứng chết lặng trong mưa😭😭 \nDù rằng bên😊😊 em đã có ai \nNhưng nơi đây anh 🤗🤗🥱vẫn còn chờ...`, event.threadID, event.messageID);