module.exports.config = {
  name: "luatbot",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "Duy (B.A.D)",
  description: "Luật Bot",
  commandCategory: "Box Chat",
  usages: "luatbot",
  cooldowns: 5,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
};

module.exports.run = async({api,event,args,client,Users,Threads,__GLOBAL,Currencies}) => {
const axios = global.nodemodule["axios"];
const request = global.nodemodule["request"];
const fs = global.nodemodule["fs-extra"];
  var link = [
"https://i.postimg.cc/W4bRSYxb/62eb67edabd1648f3dc010.jpg",
"https://i.postimg.cc/vTmkt4Kq/004aab23822f4d71143e8.jpg",
"https://i.postimg.cc/NG83qcYf/0mCTvKZ.jpg",
"https://i.postimg.cc/hPcqfGMd/0wizCbR.jpg",
"https://i.postimg.cc/pr17G2b2/1ffeae90879c48c2118d12.jpg",
"https://i.postimg.cc/X7q6wPSj/1P55PQ5.jpg",
"https://i.postimg.cc/qBjd6TFD/2IiqHC1.jpg",
"https://i.postimg.cc/Zq7qLd72/2mQSGKi.jpg",
"https://i.postimg.cc/tJ7W5bNt/2QZHfKi.jpg",
"https://i.postimg.cc/DZpbmD3W/2ZZrpkq.jpg",
"https://i.postimg.cc/ydhsb3v7/30ll2w8.jpg",
"https://i.postimg.cc/cCjYkzDq/3b8HVDz.jpg",
"https://i.postimg.cc/BQKJ1yfr/3DZKX4f.jpg",
"https://i.postimg.cc/MHsfMLkM/3FavLt7.jpg",
"https://i.postimg.cc/J7bLrX38/3ITbAwb.jpg",
"https://i.postimg.cc/XN2T7gZT/416dea1dc3110c4f550024.jpg",
"https://i.postimg.cc/ncCNsQBM/43e4718d588197dfce9010.jpg",
"https://i.postimg.cc/ZK226KxH/44982ae903e5ccbb95f417.jpg",
"https://i.postimg.cc/63Zy5QcP/4aO4q18.jpg",
"https://i.postimg.cc/JhbfrVJq/4oEFZjF.jpg",
"https://i.postimg.cc/3JRv53pg/4rVr3TV.jpg",
"https://i.postimg.cc/0j9H2zx5/4Uf7yOy.jpg",
"https://i.postimg.cc/rFkts5vN/4XpKFsN.jpg",
"https://i.postimg.cc/6pZScJHX/52ba66cb4fc78099d9d616.jpg",
"https://i.postimg.cc/7hTr0Cd3/5OWq207.jpg",
"https://i.postimg.cc/FKQ6nWqJ/64b725dd0cd1c38f9ac07.jpg",
"https://i.postimg.cc/xTvM36KZ/7YMf4mV.jpg",
"https://i.postimg.cc/YC7j2kLn/8HCm0cO.jpg",
"https://i.postimg.cc/Hk7GN7kF/8PdEhwN.jpg",
"https://i.postimg.cc/Tw6DZmqw/8xQWAvb.jpg",
"https://i.postimg.cc/DzqWd0kK/9FU9BmU.jpg",
"https://i.postimg.cc/ncycRx1V/9iGBRwr.jpg",
"https://i.postimg.cc/zf0NrYTg/9NHjJIr.jpg",
"https://i.postimg.cc/3ryZmjfM/A41JHAf.jpg",
"https://i.postimg.cc/tgtc0dQv/aa85e0e9c9e506bb5ff427.jpg",
"https://i.postimg.cc/Z5fZkh8y/AiQI8ji.jpg",
"https://i.postimg.cc/rwgy84ks/bDXZ7K5.jpg",
"https://i.postimg.cc/xCf49k9f/bee99398ba9475ca2c8515.jpg",
"https://i.postimg.cc/RFTxR5ZF/Bepi6cZ.jpg",
"https://i.postimg.cc/K8b766GF/bH2gLBG.jpg",
"https://i.postimg.cc/HnJdzvc7/BKC5g6y.jpg",
"https://i.postimg.cc/L5h67675/bkFA67N.jpg",
"https://i.postimg.cc/V6gdphkG/BRosV3A.jpg",
"https://i.postimg.cc/xTccptD5/c1jWpDB.jpg",
"https://i.postimg.cc/SK3nh968/C7hE9FP.jpg",
"https://i.postimg.cc/gJhP6Xfv/cEroOxo.jpg",
"https://i.postimg.cc/J4kB4P6n/cHH6rTl.jpg",
"https://i.postimg.cc/sx09dxgN/CqHx5G3.jpg",
"https://i.postimg.cc/tJfCHGQ5/Cs4MkUV.jpg",
"https://i.postimg.cc/76wNSjRm/d8yfkjL.jpg",
"https://i.postimg.cc/BZDKJmwv/dM3He80.jpg",
"https://i.postimg.cc/P5nTb4tP/dMyrPeR.jpg",
"https://i.postimg.cc/mrFndx84/DsliVjC.jpg",
"https://i.postimg.cc/PqGpwZ74/DsyUu49.jpg",
"https://i.postimg.cc/d1ZJmSTZ/dT5HoK9.jpg",
"https://i.postimg.cc/hP2Pnxgj/dztFRd7.jpg",
"https://i.postimg.cc/DypFHTd4/e5oK2ND.jpg",
"https://i.postimg.cc/rm7xQbnB/eBfPxQk.jpg",
"https://i.postimg.cc/43dcZZrC/fFinnH5.jpg",
"https://i.postimg.cc/CK3xtg0s/FgT5IvE.jpg",
"https://i.postimg.cc/C5KHQkS8/fhrnMHt.jpg",
"https://i.postimg.cc/T3yGX4C7/FKGxYuS.jpg",
"https://i.postimg.cc/rs8MXyPx/fn24mug.jpg",
"https://i.postimg.cc/qRvkhvpw/FO65fzi.jpg",
"https://i.postimg.cc/NFbCyQf6/fwM0YCo.jpg",
"https://i.postimg.cc/5yNdK7Xm/Fx6TzgQ.jpg",
"https://i.postimg.cc/wj3xjvTk/FxchIKS.jpg",
"https://i.postimg.cc/mZcP8mGw/g0XLrwK.jpg",
"https://i.postimg.cc/m2jhrJ3T/gJUiO3H.jpg",
"https://i.postimg.cc/YjKK3rBJ/gql5xEk.jpg",
"https://i.postimg.cc/JnCRx53T/gqsPMnJ.jpg",
"https://i.postimg.cc/cLGtKw2c/haopYQL.jpg",
"https://i.postimg.cc/gJg2N6g1/hJuhfT8.jpg",
"https://i.postimg.cc/rw5WgQxb/HRx6vj2.jpg",
"https://i.postimg.cc/Dz8hnY6p/i1fQVol.jpg",
"https://i.postimg.cc/ncJnB2VM/I8HytB4.jpg",
"https://i.postimg.cc/65mzFj7p/IJWR5tr.jpg",
"https://i.postimg.cc/DZPXFZBc/IMSU2FJ.jpg",
"https://i.postimg.cc/fbBVgFLH/InNKEZm.jpg",
"https://i.postimg.cc/BZCV7Bcj/iPSvMsA.jpg",
"https://i.postimg.cc/RZvfswdZ/IViRBcE.jpg",
"https://i.postimg.cc/K8CLDC1t/IxF9h6A.jpg",
"https://i.postimg.cc/SN2xfRCt/JFdiZPE.jpg",
"https://i.postimg.cc/6phqySd9/JPr6Vjv.jpg",
"https://i.postimg.cc/y8RhtV4L/JSozXDn.jpg",
"https://i.postimg.cc/7hDYHnfC/jXjhqP5.jpg",
"https://i.postimg.cc/7PQgLCqB/K8Vf1to.jpg",
"https://i.postimg.cc/q7nmssvM/KAuo1xc.jpg",
"https://i.postimg.cc/BQYw4Zzs/kgFkxpt.jpg",
"https://i.postimg.cc/7P7x5dkp/KIIWzuP.jpg",
"https://i.postimg.cc/T1rLQPWb/kU9X5uc.jpg",
"https://i.postimg.cc/7L7zsXzd/KxARtAY.jpg",
"https://i.postimg.cc/FRzYtZkh/l3gmjF9.jpg",
"https://i.postimg.cc/g08Wx693/lcffehu.jpg",
"https://i.postimg.cc/SKF0bNXR/lifdLYH.jpg",
"https://i.postimg.cc/RVkKcj6K/lIpZNy7.jpg",
"https://i.postimg.cc/WbThTTk9/llUTK6s.jpg",
"https://i.postimg.cc/GmTTtzXt/LTmfxeo.jpg",
"https://i.postimg.cc/rpC1yQpW/lywnLQh.jpg",
"https://i.postimg.cc/JnFWs367/M6ukxPZ.jpg",
"https://i.postimg.cc/L80XtP07/mDas8Gz.jpg",
"https://i.postimg.cc/hG5dt6BX/MgDGqwI.jpg",
"https://i.postimg.cc/T2rpzppL/MMYYUOv.jpg",
"https://i.postimg.cc/sXst164R/NC9Xu3c.jpg",
"https://i.postimg.cc/13MFL47c/NKjA7Kq.jpg",
"https://i.postimg.cc/ZqcNznfx/NKU66Da.jpg",
"https://i.postimg.cc/mDgHL4Jf/nmCcY9i.jpg",
"https://i.postimg.cc/cCc2QQT8/nmvSmgA.jpg",
"https://i.postimg.cc/nh9Tx47Y/NQvTGX7.jpg",
"https://i.postimg.cc/zDdkRtFF/nSdyduB.jpg",
"https://i.postimg.cc/y87Y4P22/NuBZ2ew.jpg",
"https://i.postimg.cc/HkPGZ9mw/o6AF8DO.jpg",
"https://i.postimg.cc/DzHTZdYv/oaCkjvr.jpg",
"https://i.postimg.cc/WzQFwk3T/oJUUfBX.jpg",
"https://i.postimg.cc/ydKzcYBt/ol2VDdR.jpg",
"https://i.postimg.cc/rwDZmX64/ovavB03.jpg",
"https://i.postimg.cc/wjPqyp1Y/P73sgEK.jpg",
"https://i.postimg.cc/CKVCVWwS/PycHFqC.jpg",
"https://i.postimg.cc/L4ZszhzQ/q7JUZ2Q.jpg",
"https://i.postimg.cc/c4yf3p8Y/QFtwH3u.jpg",
"https://i.postimg.cc/GmptTKzG/QmeOeAm.jpg",
"https://i.postimg.cc/ZYDqNpBd/QN1SzhB.jpg",
"https://i.postimg.cc/vHrHNj2W/rBlFtcn.jpg",
"https://i.postimg.cc/9fMmzfmp/RUKKFsZ.jpg",
"https://i.postimg.cc/QdN9khNB/s1Mi1wX.jpg",
"https://i.postimg.cc/DzX21MGJ/ScNfipI.jpg",
"https://i.postimg.cc/KjcJhCrR/sf6bGUi.jpg",
"https://i.postimg.cc/Gh8vTc2b/SFXLEQM.jpg",
"https://i.postimg.cc/tJV7J4zf/sh8zM3d.jpg",
"https://i.postimg.cc/fTr0M1j1/sIDlURq.jpg",
"https://i.postimg.cc/hvHg58TZ/SiudRTz.jpg",
"https://i.postimg.cc/W301cHbL/SVnb6eI.jpg",
"https://i.postimg.cc/qMRjbVvF/t3LRpAd.jpg",
"https://i.postimg.cc/RVNL17P5/TavhaCC.jpg",
"https://i.postimg.cc/c4zyTc0Q/u8CEGaU.jpg",
"https://i.postimg.cc/Jn5PgRXf/UE2x39t.jpg",
"https://i.postimg.cc/FRkJdprD/UY2vZLH.jpg",
"https://i.postimg.cc/Z51mYxQT/v8hq0BG.jpg",
"https://i.postimg.cc/W4WMJtMb/VL9DQxu.jpg",
"https://i.postimg.cc/MT5m5d2x/w8jNdWT.jpg",
"https://i.postimg.cc/m28Kkytv/wrmnTLB.jpg",
"https://i.postimg.cc/8cFfvHTZ/wTSnzSX.jpg",
"https://i.postimg.cc/YShvZRWM/wzvAdVR.jpg",
"https://i.postimg.cc/wxP6MzZ5/xFo96Mf.jpg",
"https://i.postimg.cc/t4r1Bw7B/XjlRI28.jpg",
"https://i.postimg.cc/525Y8jMW/xqymKfp.jpg",
"https://i.postimg.cc/C5NMznqc/ye4089A.jpg",
"https://i.postimg.cc/Bb3RLh50/YNd3cfi.jpg",
"https://i.postimg.cc/kGrqjFx1/yrDSC9C.jpg",
"https://i.postimg.cc/BvQT62PV/yzbZi9Z.jpg",
"https://i.postimg.cc/SsPJmMcC/Zd1dzsJ.jpg",
"https://i.postimg.cc/rsSc70j8/ZeAifCC.jpg",
"https://i.postimg.cc/66H8hFST/zWm8WwA.jpg",
  ];
	  var callback = () => api.sendMessage({body:`💖 𝐋𝐔𝐀̣̂𝐓 𝐒𝐔̛̉ 𝐃𝐔̣𝐍𝐆 𝐁𝐎𝐓 💖 ⚠ 𝐕𝐮𝐢 𝐥𝐨̀𝐧𝐠 𝐜𝐡𝐚̂́𝐩 𝐡𝐚̀𝐧𝐡 𝐧𝐠𝐡𝐢𝐞̂𝐦 𝐜𝐡𝐢̉𝐧𝐡 𝐭𝐫𝐚́𝐧𝐡 𝐛𝐢̣ 𝐛𝐚𝐧\n𝟏: 𝐊𝐡𝐨̂𝐧𝐠 𝐬𝐩𝐚𝐦 𝐥𝐞̣̂𝐧𝐡 𝐛𝐨𝐭, 𝐬𝐩𝐚𝐦 𝐩𝐫𝐞𝐟𝐢𝐱 𝐪𝐮𝐚́ 𝐧𝐡𝐢𝐞̂̀𝐮 𝐠𝐚̂𝐲 𝐝𝐢𝐞 𝐛𝐨𝐭, 𝐜𝐡𝐞𝐜𝐤𝐩𝐨𝐢𝐧𝐭 🚫\n𝟐: 𝐊𝐡𝐨̂𝐧𝐠 𝐠𝐚̂𝐲 𝐰𝐚𝐫 𝐯𝐨̛́𝐢 𝐛𝐨𝐭 (𝐬𝐢𝐦, 𝐧𝐢𝐧𝐨) 𝐯𝐢̀ 𝐧𝐨́ 𝐤𝐡𝐨̂𝐧𝐠 𝐩𝐡𝐚̉𝐢 𝐧𝐠𝐮̛𝐨̛̀𝐢 𝐝𝐮̀𝐧𝐠 𝐭𝐮̛𝐨̛𝐧𝐠 𝐭𝐚́𝐜 𝐭𝐡𝐚̣̂𝐭 !\n𝟑: 𝐊𝐡𝐨̂𝐧𝐠 𝐥𝐚̣𝐦 𝐝𝐮̣𝐧𝐠 𝐛𝐨𝐭 𝐯𝐚̀𝐨 𝐲́ 𝐱𝐚̂́𝐮\n𝟒: 𝐓𝐡𝐨̛̀𝐢 𝐠𝐢𝐚𝐧 𝐬𝐮̛̉ 𝐝𝐮̣𝐧𝐠 𝐥𝐞̣̂𝐧𝐡 𝟗 𝐥𝐚̂̀𝐧/𝟏𝟑𝟎𝐬\n𝟓: 𝐓𝐫𝐮̛𝐨̛̀𝐧𝐠 𝐡𝐨̛̣𝐩 𝐛𝐢̣ 𝐛𝐚𝐧 𝐚𝐝𝐦𝐢𝐧 𝐬𝐞̃ 𝐤𝐡𝐨̂𝐧𝐠 𝐠𝐢𝐚̉𝐢 𝐪𝐮𝐲𝐞̂́𝐭 𝐦𝐨̛̉ 𝐛𝐚𝐧 𝐧𝐡𝐞́.\n𝟔: 𝐂𝐚̂́𝐦 𝐜𝐡𝐮̛̉𝐢 𝐛𝐨𝐭 𝐝𝐮̛𝐨̛́𝐢 𝐦𝐨̣𝐢 𝐡𝐢̀𝐧𝐡 𝐭𝐡𝐮̛́𝐜, 𝐜𝐡𝐮̛̉𝐢 𝐭𝐡𝐨𝐚̉𝐢 𝐦𝐚́𝐢 𝐧𝐞̂́𝐮 𝐧𝐡𝐮̛ 𝐛𝐚̣𝐧 𝐤𝐡𝐨̂𝐧𝐠 𝐦𝐮𝐨̂́𝐧 𝐱𝐚̀𝐢 𝐛𝐨𝐭 𝐯𝐚̀ 𝐲́ 𝐭𝐡𝐮̛́𝐜 𝐜𝐮̉𝐚 𝐛𝐚̣𝐧 𝐧𝐡𝐮̛ 𝐜𝐨𝐧 𝐜𝐚̣̆𝐜\n𝐇𝐚̃𝐲 𝐬𝐮̛̉ 𝐝𝐮̣𝐧𝐠 𝐛𝐨𝐭 𝐦𝐨̣̂𝐭 𝐜𝐚́𝐜𝐡 𝐭𝐡𝐨̂𝐧𝐠 𝐦𝐢𝐧𝐡 𝐯𝐚̀ 𝐲́ 𝐭𝐡𝐮̛́𝐜 🌺`,attachment: fs.createReadStream(__dirname + "/cache/5.jpg")}, event.threadID, () => fs.unlinkSync(__dirname + "/cache/5.jpg")); 
      return request(encodeURI(link[Math.floor(Math.random() * link.length)])).pipe(fs.createWriteStream(__dirname+"/cache/5.jpg")).on("close",() => callback());
   };